server:
  port: 8122
spring:
  profiles:
    active: dev
plaintext: lowi


logging:
  file:
    path: ./logs/javaLowiAdmin
  config: classpath:logback-spring.xml
mybatis-plus:
  global-config:
    db-config:
      id-type: auto    #id自增
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql